In [8]:
import numpy as np

**“Вычисления с помощью Numpy.**”
**Задание 1.**
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [9]:
a = np.array([[1,2,3,3,1],
             [6,8,11,10,7]])
print(a)
print("Размерность a: {}".format(a.ndim))
mean_a = a.mean(axis=1)
print("Среднее значение строк, (наблюдение): {}".format(mean_a))

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
Размерность a: 2
Среднее значение строк, (наблюдение): [2.  8.4]


**Задание 2.**
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [10]:
a_centered = a.T - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


**Задание 3.**
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [11]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
print(a_centered_sp)

a_centered_sp = a_centered_sp / (a.shape[0]-1)
print(a_centered_sp)

8.0
8.0


**Задание 4.**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.


In [ ]:
np.cov(a.T)[0,1]

15.0